### ISSUE TITLE
No su.py in reposatory

### ISSUE THREAD

**Issue by secrakib** [nishant0820/Student-Result-Management-System#1]
Do not understand what you are trying to say here
Before running dashboard.py, make su.py file firre to run create_dbst and create a folder named images.

**Comment by nishant0820** [comment]
I am just saying to create a database first, for that you should run the create_db.py file first and just create two folders in the project named bill and images, and inside images store your assets and in bills, it will save all your bills info

**Comment by nishant0820** [comment]
It was my mistake. Now I have corrected it. Now, you can go through it. If you stuck somewhere else, feel free to ask.
