### ISSUE TITLE
Report.py Don't support Long numbers like 2020331520

### ISSUE THREAD

**Issue by secrakib** [nishant0820/Student-Result-Management-System#2]

**Comment by nishant0820** [comment]
I am not getting your issue correctly. Explain it completely

**Comment by secrakib** [comment]
Register a student with roll no greater than one digit like 101,2020331520,7654.

Then try to access it via report. You will see that numbers greater than one digit can't be accessed. 

Your database only support roll number with one digit length for report.py

**Comment by nishant0820** [comment]
Because of the column type in the database, you can change it accordingly.

Thank You!!!
